"""VANO routing providers, candidate generation and traffic.

Extracted from the historical monolithic app.py without changing route bodies or
business rules. Runtime dependencies are injected once during application startup.
"""
from vano.bootstrap import inject as _vano_inject
_vano_inject(globals())
del _vano_inject

def sanitize_depart_at(value):
    value = (value or "now").strip()
    if value == "now":
        return "now"
    # ISO 8601 enxuto; o Mapbox calcula o fuso quando não há offset.
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:?\d{2})?", value):
        return value[:32]
    return "now"


def sanitize_start_bearing(value):
    """Normalize a GPS heading for provider-side start-direction matching."""
    try:
        bearing = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(bearing):
        return None
    return round(bearing % 360.0, 1)


def sanitize_start_speed(value):
    try:
        speed = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(speed) or speed < 0:
        return None
    return round(min(speed, 70.0), 2)


def _bearing_delta_deg(a, b):
    return abs(((float(a) - float(b) + 180.0) % 360.0) - 180.0)


def _route_initial_bearing(route):
    coords = ((route or {}).get("geometry") or {}).get("coordinates") or []
    valid = []
    for c in coords[:80]:
        try:
            lon, lat = float(c[0]), float(c[1])
        except (TypeError, ValueError, IndexError):
            continue
        if -180 <= lon <= 180 and -90 <= lat <= 90:
            valid.append((lon, lat))
    if len(valid) < 2:
        return None
    a = valid[0]
    for b in valid[1:]:
        if haversine_m(a[1], a[0], b[1], b[0]) < 14:
            continue
        y = math.sin(math.radians(b[0]-a[0])) * math.cos(math.radians(b[1]))
        x = math.cos(math.radians(a[1])) * math.sin(math.radians(b[1])) - math.sin(math.radians(a[1])) * math.cos(math.radians(b[1])) * math.cos(math.radians(b[0]-a[0]))
        return (math.degrees(math.atan2(y, x)) + 360.0) % 360.0
    return None


def apply_start_direction_guard(routes, start_bearing=None, start_speed=None, moving_threshold=1.2):
    """Reject variants that begin almost opposite to a moving vehicle's heading.

    Mapbox's bearings parameter is the primary constraint. This second pass protects
    the custom micro-route pool too, because some variants are generated by helper
    calls that do not necessarily carry live GPS context. If every candidate fails,
    keep the provider set rather than leaving the user without a route.
    """
    routes = list(routes or [])
    bearing = sanitize_start_bearing(start_bearing)
    speed = sanitize_start_speed(start_speed)
    if bearing is None or speed is None or speed < moving_threshold or not routes:
        return routes, {"active": False, "rejected": 0, "bearing": bearing, "speed_mps": speed}
    accepted, rejected = [], 0
    for route in routes:
        rb = _route_initial_bearing(route)
        delta = _bearing_delta_deg(rb, bearing) if rb is not None else None
        route["_start_direction_bearing"] = round(rb, 1) if rb is not None else None
        route["_start_direction_delta"] = round(delta, 1) if delta is not None else None
        route["_start_direction_ok"] = bool(delta is None or delta <= 112.0)
        if route["_start_direction_ok"]:
            accepted.append(route)
        else:
            rejected += 1
    if not accepted:
        return routes, {"active": True, "rejected": 0, "bearing": bearing, "speed_mps": speed, "fallback": "provider-set"}
    return accepted, {"active": True, "rejected": rejected, "bearing": bearing, "speed_mps": speed}



def _ors_language():
    lang = (preferred_language() or "pt-BR").lower()
    return "pt" if lang.startswith("pt") else (lang.split("-", 1)[0] or "en")


def _ors_step_type(step_type):
    # ORS encodes maneuver type as an integer. We keep broad maneuver labels only;
    # the human instruction string remains the source of truth for guidance/voice.
    mapping = {
        0: ("turn", "left"), 1: ("turn", "right"), 2: ("turn", "sharp-left"),
        3: ("turn", "sharp-right"), 4: ("turn", "slight-left"), 5: ("turn", "slight-right"),
        6: ("continue", "straight"), 7: ("roundabout", ""), 8: ("roundabout", ""),
        10: ("arrive", ""), 11: ("depart", ""), 12: ("keep", "left"), 13: ("keep", "right"),
    }
    try:
        return mapping.get(int(step_type), ("continue", ""))
    except Exception:
        return ("continue", "")


def openrouteservice_routes(start_lon, start_lat, end_lon, end_lat, travel_profile="walking", alternatives=True):
    """Secondary routing provider used only when Mapbox cannot produce a route.

    Uses the official HeiGIT/openrouteservice endpoint. Returned data is normalized
    to the subset of the Mapbox route shape that Vano Maps already consumes.
    """
    if not OPENROUTESERVICE_API_KEY:
        raise RuntimeError("Fallback openrouteservice não configurado (OPENROUTESERVICE_API_KEY).")
    profiles = {"walking": "foot-walking", "cycling": "cycling-regular", "driving": "driving-car", "motorcycle": "driving-car"}
    profile = profiles.get(travel_profile, "foot-walking")
    url = f"{OPENROUTESERVICE_URL}/{profile}/geojson"
    body = {
        "coordinates": [[float(start_lon), float(start_lat)], [float(end_lon), float(end_lat)]],
        "instructions": True,
        "instructions_format": "text",
        "language": _ors_language(),
        "preference": "fastest",
    }
    direct_km = haversine_m(start_lat, start_lon, end_lat, end_lon) / 1000.0
    if alternatives and direct_km <= 95:
        body["alternative_routes"] = {"target_count": 3, "weight_factor": 1.45, "share_factor": 0.7}
    headers = {"Authorization": OPENROUTESERVICE_API_KEY, "Content-Type": "application/json", "Accept": "application/geo+json, application/json"}
    try:
        r = requests.post(url, json=body, headers=headers, timeout=22)
        if r.status_code >= 400 and "alternative_routes" in body:
            body.pop("alternative_routes", None)
            r = requests.post(url, json=body, headers=headers, timeout=22)
        r.raise_for_status()
        data = r.json() or {}
    except Exception as exc:
        raise RuntimeError(f"openrouteservice indisponível: {exc}") from exc
    routes = []
    for feature in (data.get("features") or [])[:4]:
        props = feature.get("properties") or {}
        summary = props.get("summary") or {}
        geometry = feature.get("geometry") or {}
        coords = geometry.get("coordinates") or []
        if geometry.get("type") != "LineString" or len(coords) < 2:
            continue
        normalized_steps = []
        for segment in props.get("segments") or []:
            for st in segment.get("steps") or []:
                mtype, modifier = _ors_step_type(st.get("type"))
                way = st.get("way_points") or []
                loc = None
                if way:
                    try:
                        idx = max(0, min(len(coords)-1, int(way[-1])))
                        loc = coords[idx]
                    except Exception:
                        loc = None
                normalized_steps.append({
                    "distance": float(st.get("distance") or 0),
                    "duration": float(st.get("duration") or 0),
                    "name": str(st.get("name") or ""),
                    "maneuver": {
                        "instruction": str(st.get("instruction") or "Continue pela rota"),
                        "type": mtype, "modifier": modifier,
                        "location": loc or coords[0],
                    },
                    "voiceInstructions": [{
                        "distanceAlongGeometry": float(st.get("distance") or 0),
                        "announcement": str(st.get("instruction") or "Continue pela rota"),
                    }],
                    "intersections": [],
                })
        routes.append({
            "distance": float(summary.get("distance") or 0),
            "duration": float(summary.get("duration") or 0),
            "geometry": {"type": "LineString", "coordinates": coords},
            "legs": [{"steps": normalized_steps, "annotation": {}}],
            "_profile_used": f"openrouteservice-{profile}",
            "_provider": "openrouteservice",
            "_traffic_source": "unavailable",
        })
    if not routes:
        raise RuntimeError("openrouteservice não encontrou rota.")
    return routes


def osrm_routes(start_lon, start_lat, end_lon, end_lat, travel_profile="driving", alternatives=True):
    """Optional final fallback for a user-configured/self-hosted OSRM server."""
    if not OSRM_BASE_URL:
        raise RuntimeError("OSRM fallback não configurado.")
    profile = "driving" if is_motorized_profile(travel_profile) else ("cycling" if travel_profile == "cycling" else "walking")
    url = f"{OSRM_BASE_URL}/route/v1/{profile}/{float(start_lon):.6f},{float(start_lat):.6f};{float(end_lon):.6f},{float(end_lat):.6f}"
    params = {"alternatives": "true" if alternatives else "false", "steps": "true", "overview": "full", "geometries": "geojson"}
    try:
        r = requests.get(url, params=params, timeout=18); r.raise_for_status(); data = r.json() or {}
    except Exception as exc:
        raise RuntimeError(f"OSRM indisponível: {exc}") from exc
    if data.get("code") != "Ok":
        raise RuntimeError(data.get("message") or "OSRM não encontrou rota.")
    routes=[]
    for raw in (data.get("routes") or [])[:4]:
        raw["_profile_used"] = f"osrm-{profile}"; raw["_provider"] = "osrm"; raw["_traffic_source"] = "unavailable"
        routes.append(raw)
    if not routes: raise RuntimeError("OSRM não encontrou rota.")
    return routes


def fallback_routes(start_lon, start_lat, end_lon, end_lat, travel_profile="walking", alternatives=True):
    errors=[]
    if OPENROUTESERVICE_API_KEY:
        try: return openrouteservice_routes(start_lon,start_lat,end_lon,end_lat,travel_profile,alternatives)
        except Exception as exc: errors.append(str(exc))
    if OSRM_BASE_URL:
        try: return osrm_routes(start_lon,start_lat,end_lon,end_lat,travel_profile,alternatives)
        except Exception as exc: errors.append(str(exc))
    raise RuntimeError("Nenhum provedor secundário de rotas disponível." + (" " + " | ".join(errors) if errors else ""))



def motorized_candidate_routes(start_lon, start_lat, end_lon, end_lat, travel_profile="driving", depart_at="now", micro_budget=8, mapbox_exclusions=None, extra_excludes=None, start_bearing=None, start_speed=None, reroute=False):
    """V48 Mapbox-only candidate engine.

    Mapbox provides the traffic-aware base alternatives; Vano Maps then expands them with
    nearby block/corridor micro-variants before the selected policy chooses a winner.
    """
    routes = mapbox_routes(
        start_lon, start_lat, end_lon, end_lat, travel_profile,
        depart_at=depart_at, exclusions=mapbox_exclusions, alternatives=True,
        extra_excludes=extra_excludes, start_bearing=start_bearing, start_speed=start_speed, reroute=reroute,
    )
    return routes, "mapbox", len(routes)

def mapbox_routes(start_lon, start_lat, end_lon, end_lat, travel_profile="walking", depart_at="now", exclusions=None, alternatives=True, extra_excludes=None, start_bearing=None, start_speed=None, reroute=False):
    profile_map = {
        "walking": "walking",
        "cycling": "cycling",
        "driving": "driving-traffic",
        # Mapbox has no dedicated motorcycle Directions profile. We use the
        # motorized traffic graph and apply motorcycle-specific safety/scoring
        # in Vano Maps instead of pretending bike routing is appropriate.
        "motorcycle": "driving-traffic",
    }
    profile = profile_map.get(travel_profile, "walking")
    coords = f"{start_lon},{start_lat};{end_lon},{end_lat}"
    params = {
        "alternatives": "true" if alternatives else "false",
        "steps": "true",
        "banner_instructions": "true",
        "voice_instructions": "true",
        "voice_units": "metric",
        "geometries": "geojson",
        "overview": "full",
        "language": mapbox_language(),
        "annotations": "distance,duration,speed",
    }
    if profile == "driving-traffic":
        params["annotations"] = "distance,duration,speed,congestion,congestion_numeric,maxspeed,closure"
        params["notifications"] = "all"
        params["depart_at"] = sanitize_depart_at(depart_at)
        # Live direction guard: when the GPS says the vehicle is actually moving,
        # constrain the first snapped road segment to the vehicle heading. This is
        # specifically recommended by Mapbox for rerouting vehicles.
        bearing = sanitize_start_bearing(start_bearing)
        speed = sanitize_start_speed(start_speed)
        direction_guard_active = bearing is not None and speed is not None and speed >= 1.2
        if direction_guard_active:
            params["bearings"] = f"{bearing:.0f},70;"
            params["continue_straight"] = "true"
            if reroute:
                params["avoid_maneuver_radius"] = str(int(clamp(45 + speed * 7.0, 45, 160)))
        excludes = []
        for value in (extra_excludes or []):
            value = str(value or "").strip().lower()
            if value in {"unpaved", "toll", "ferry", "motorway", "tunnel", "cash_only_tolls"} and value not in excludes:
                excludes.append(value)
        if exclusions:
            # Mapbox custom-location exclusions are best-effort; the response is
            # validated again before a professional route is selected.
            for lon, lat in exclusions[:18]:
                excludes.append(f"point({float(lon):.6f} {float(lat):.6f})")
        if excludes:
            params["exclude"] = ",".join(excludes)
    direct_km = haversine_m(start_lat, start_lon, end_lat, end_lon) / 1000.0
    timeout = 28 if direct_km > 1200 else 20
    cache_key = (
        round(float(start_lon), 5), round(float(start_lat), 5),
        round(float(end_lon), 5), round(float(end_lat), 5),
        travel_profile, sanitize_depart_at(depart_at), bool(alternatives), str(params.get("language") or ""),
        str(params.get("bearings") or ""), str(params.get("avoid_maneuver_radius") or ""), bool(reroute),
        tuple(sorted(str(x) for x in (extra_excludes or []))),
        tuple((round(float(x[0]), 5), round(float(x[1]), 5)) for x in (exclusions or [])[:18]),
    )
    cache_ttl = _ROUTE_PROVIDER_CACHE_TTL_LIVE if (is_motorized_profile(travel_profile) and sanitize_depart_at(depart_at) == "now") else _ROUTE_PROVIDER_CACHE_TTL_STATIC
    cached = _route_cache_get(cache_key, cache_ttl)
    if cached is not None:
        return cached
    used_profile = profile
    try:
        data = _route_mapbox_get(f"{MAPBOX_DIRECTIONS_URL}/{profile}/{coords}", params, timeout=timeout)
    except Exception as primary_exc:
        if profile == "driving-traffic":
            try:
                fallback = dict(params)
                fallback.pop("depart_at", None)
                fallback["annotations"] = "distance,duration,speed,maxspeed"
                data = _route_mapbox_get(f"{MAPBOX_DIRECTIONS_URL}/driving/{coords}", fallback, timeout=timeout)
                used_profile = "driving"
            except Exception:
                routes = fallback_routes(start_lon, start_lat, end_lon, end_lat, travel_profile, alternatives)
                _route_cache_put(cache_key, routes)
                return routes
        else:
            routes = fallback_routes(start_lon, start_lat, end_lon, end_lat, travel_profile, alternatives)
            _route_cache_put(cache_key, routes)
            return routes
    if data.get("code") != "Ok" and profile == "driving-traffic":
        try:
            fallback = dict(params)
            fallback.pop("depart_at", None)
            fallback["annotations"] = "distance,duration,speed,maxspeed"
            data = _route_mapbox_get(f"{MAPBOX_DIRECTIONS_URL}/driving/{coords}", fallback, timeout=timeout)
            used_profile = "driving"
        except Exception:
            routes = fallback_routes(start_lon, start_lat, end_lon, end_lat, travel_profile, alternatives)
            _route_cache_put(cache_key, routes)
            return routes
    if data.get("code") != "Ok":
        try:
            routes = fallback_routes(start_lon, start_lat, end_lon, end_lat, travel_profile, alternatives)
            _route_cache_put(cache_key, routes)
            return routes
        except Exception as fallback_exc:
            raise RuntimeError((data.get("message") or "Nenhuma rota disponível") + f" · fallback: {fallback_exc}")
    routes = data.get("routes", [])
    if not routes:
        try:
            routes = fallback_routes(start_lon, start_lat, end_lon, end_lat, travel_profile, alternatives)
            _route_cache_put(cache_key, routes)
            return routes
        except Exception:
            pass
    for route in routes:
        route["_profile_used"] = used_profile
        route["_provider"] = "mapbox"
    _route_cache_put(cache_key, routes)
    return routes


def mapbox_routes_via(points, depart_at="now", start_bearing=None, start_speed=None, reroute=False):
    """Recalcula o ETA de uma rota atual usando pontos silenciosos como guias do caminho."""
    clean = []
    for item in (points or [])[:8]:
        try:
            lon, lat = float(item[0]), float(item[1])
        except Exception:
            continue
        if -180 <= lon <= 180 and -90 <= lat <= 90:
            if not clean or haversine_m(clean[-1][1], clean[-1][0], lat, lon) > 15:
                clean.append([lon, lat])
    if len(clean) < 2:
        raise RuntimeError("Pontos insuficientes para estimar a rota atual.")
    coords = ";".join(f"{lon:.6f},{lat:.6f}" for lon, lat in clean)
    params = {
        "alternatives": "false",
        "steps": "true",
        "banner_instructions": "true",
        "voice_instructions": "true",
        "voice_units": "metric",
        "geometries": "geojson",
        "overview": "full",
        "language": mapbox_language(),
        "annotations": "distance,duration,speed,congestion,congestion_numeric,maxspeed,closure",
        "notifications": "all",
        "depart_at": sanitize_depart_at(depart_at),
        # Os pontos intermediários orientam o caminho sem criar chegadas/partidas artificiais.
        "waypoints": f"0;{len(clean)-1}",
    }
    bearing = sanitize_start_bearing(start_bearing)
    speed = sanitize_start_speed(start_speed)
    if bearing is not None and speed is not None and speed >= 1.2:
        params["bearings"] = ";".join([f"{bearing:.0f},70"] + [""] * (len(clean)-1))
        params["continue_straight"] = "true"
        if reroute:
            params["avoid_maneuver_radius"] = str(int(clamp(45 + speed * 7.0, 45, 160)))
    try:
        data = _route_mapbox_get(f"{MAPBOX_DIRECTIONS_URL}/driving-traffic/{coords}", params, timeout=18)
        used = "driving-traffic"
    except Exception:
        fallback = dict(params)
        fallback.pop("depart_at", None)
        fallback["annotations"] = "distance,duration,speed,maxspeed"
        data = _route_mapbox_get(f"{MAPBOX_DIRECTIONS_URL}/driving/{coords}", fallback, timeout=18)
        used = "driving"
    if data.get("code") != "Ok" or not data.get("routes"):
        raise RuntimeError(data.get("message") or "Não foi possível atualizar a rota atual.")
    route = data["routes"][0]
    route["_profile_used"] = used
    return route


def route_signature(route):
    coords = ((route or {}).get("geometry") or {}).get("coordinates") or []
    if not coords:
        return ""
    step = max(1, len(coords)//18)
    sample = coords[::step][:20]
    raw = "|".join(f"{float(c[0]):.4f},{float(c[1]):.4f}" for c in sample if len(c) >= 2)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:18]


def route_spatial_cells(route, cell_m=72):
    """Coarse geometry fingerprint: detects same-road alternatives despite polyline noise."""
    coords = ((route or {}).get("geometry") or {}).get("coordinates") or []
    valid = [(float(c[0]), float(c[1])) for c in coords if len(c) >= 2]
    if len(valid) < 2:
        return set()
    avg_lat = sum(c[1] for c in valid) / len(valid)
    lat_step = max(.00012, float(cell_m) / 110540.0)
    lon_step = max(.00012, float(cell_m) / (111320.0 * max(.22, math.cos(math.radians(avg_lat)))))
    stride = max(1, len(valid)//700)
    cells = {(int(round(lat/lat_step)), int(round(lon/lon_step))) for lon,lat in valid[::stride]}
    lon, lat = valid[-1]
    cells.add((int(round(lat/lat_step)), int(round(lon/lon_step))))
    return cells

def route_overlap_ratio(a, b):
    ca, cb = route_spatial_cells(a), route_spatial_cells(b)
    if not ca or not cb:
        return 1.0 if route_signature(a) == route_signature(b) else 0.0
    return len(ca & cb) / max(1, min(len(ca), len(cb)))

def select_diverse_routes(routes, max_routes=6, max_overlap=.91, sort_key=None):
    ordered = list(routes or [])
    if sort_key is not None:
        ordered.sort(key=sort_key)
    selected = []
    for route in ordered:
        if not ((route or {}).get("geometry") or {}).get("coordinates"):
            continue
        if any(route_overlap_ratio(route, other) >= max_overlap for other in selected):
            continue
        selected.append(route)
        if len(selected) >= max_routes:
            break
    return selected or ordered[:1]

def adaptive_exclusion_groups(route, budget=4):
    coords = ((route or {}).get("geometry") or {}).get("coordinates") or []
    if len(coords) < 10:
        return []
    fractions = [.24, .40, .56, .72, .84]
    points = []
    for frac in fractions:
        idx = max(2, min(len(coords)-3, int((len(coords)-1)*frac)))
        c = coords[idx]
        if len(c) >= 2:
            points.append([float(c[0]), float(c[1])])
    groups = [[p] for p in points[:max(1, budget-1)]]
    if len(points) >= 3 and budget >= 3:
        groups.append([points[1], points[-2]])
    return groups[:max(1, budget)]

def build_adaptive_corridor_routes(base_routes, start_lon, start_lat, end_lon, end_lat, depart_at="now", budget=4, base_exclusions=None, extra_excludes=None):
    """Expand the pool with block/corridor variants when provider alternatives collapse."""
    if not base_routes:
        return []
    primary = min(base_routes, key=lambda r: float(r.get("duration", 10**12)))
    groups = adaptive_exclusion_groups(primary, max(1, min(5, int(budget or 4))))
    if not groups:
        return []
    def fetch_group(group):
        try:
            found = mapbox_routes(start_lon,start_lat,end_lon,end_lat,"driving",depart_at,exclusions=(list(base_exclusions or [])+list(group))[:18],alternatives=False,extra_excludes=extra_excludes)
            if found:
                candidate = found[0]
                candidate["_adaptive_variant"] = True
                candidate["_adaptive_avoided_points"] = len(group)
                return candidate
        except Exception:
            return None
        return None
    with ThreadPoolExecutor(max_workers=min(4, len(groups))) as pool:
        fetched = list(pool.map(fetch_group, groups))
    fastest_s = max(1.0, float(primary.get("duration") or 1))
    out = []
    for candidate in fetched:
        if not candidate or float(candidate.get("duration") or 10**12) > fastest_s*1.70:
            continue
        if any(route_overlap_ratio(candidate, r) >= .91 for r in list(base_routes)+out):
            continue
        out.append(candidate)
    return out[:budget]

def ensure_adaptive_route_pool(routes, start_lon, start_lat, end_lon, end_lat, depart_at="now", target=4, budget=4, base_exclusions=None, extra_excludes=None):
    base = list(routes or [])
    if not base:
        return []
    distinct = select_diverse_routes(base, max_routes=8, max_overlap=.91, sort_key=lambda r: float(r.get("duration", 10**12)))
    # V88: Mapbox alternatives are already useful. Only probe generic corridors
    # when alternatives are sparse AND the fastest route has meaningful traffic.
    primary = min(base, key=lambda r: float(r.get("duration", 10**12)))
    traffic = route_traffic_metrics(primary)
    traffic_score = float(traffic.get("traffic_score") or 0)
    severe = int(traffic.get("severe_segments") or 0)
    duration_s = float(primary.get("duration") or 0)
    if len(distinct) < min(target, 3) and duration_s >= 420 and (traffic_score >= 42 or severe > 0):
        base.extend(build_adaptive_corridor_routes(base,start_lon,start_lat,end_lon,end_lat,depart_at,budget=min(2,budget),base_exclusions=base_exclusions,extra_excludes=extra_excludes))
    return select_diverse_routes(base, max_routes=7, max_overlap=.93, sort_key=lambda r: float(r.get("duration", 10**12)))


def route_traffic_metrics(route):
    """Turn Mapbox per-edge traffic annotations into compact route intelligence.

    The raw provider data remains the source of truth for ETA/routing. This helper
    only summarizes it for UI, route scoring and traffic-aware rerouting.
    """
    empty = {
        "traffic_score": 0, "traffic_level": "Sem dados", "congested_distance_km": 0,
        "traffic_points": [], "traffic_segments": [], "traffic_corridors": [],
        "severe_segments": 0, "traffic_delay_min": 0, "traffic_delay_pct": 0,
        "duration_typical": None, "traffic_source": route.get("_traffic_source", "mapbox-driving-traffic") if route else "mapbox-driving-traffic",
    }
    if not route:
        return dict(empty)
    geometry = (route.get("geometry") or {}).get("coordinates") or []
    if len(geometry) < 2:
        return dict(empty)

    weights = {"unknown": 15, "low": 15, "moderate": 48, "heavy": 76, "severe": 94}
    samples = []
    step_ranges = []
    global_m = 0.0
    severe_indices = []
    closures_count = 0
    incidents_count = 0

    # Step ranges give human-readable street names without an extra geocoding call.
    for leg in route.get("legs", []) or []:
        leg_start = global_m
        for step in leg.get("steps", []) or []:
            d = max(0.0, float(step.get("distance") or 0))
            step_ranges.append({
                "start": global_m,
                "end": global_m + d,
                "street": str(step.get("name") or "").strip()[:140] or "Trecho da rota",
                "duration": max(0.0, float(step.get("duration") or 0)),
                "duration_typical": max(0.0, float(step.get("duration_typical") or 0)) if step.get("duration_typical") is not None else None,
            })
            global_m += d
        # Annotation distance is the best alignment reference; correct any small
        # difference between sum(step.distance) and the leg annotation total.
        ann = leg.get("annotation") or {}
        nums = list(ann.get("congestion_numeric") or [])
        labels = list(ann.get("congestion") or [])
        distances = list(ann.get("distance") or [])
        n = max(len(nums), len(labels), len(distances))
        ann_cursor = leg_start
        for i in range(n):
            d = float(distances[i]) if i < len(distances) and distances[i] is not None else 1.0
            d = max(0.2, d)
            numeric = nums[i] if i < len(nums) else None
            label = str(labels[i]).lower() if i < len(labels) and labels[i] else "unknown"
            score = clamp(float(numeric) if numeric is not None else float(weights.get(label, 20)), 0, 100)
            samples.append({"start": ann_cursor, "end": ann_cursor + d, "distance": d, "score": score, "label": label})
            if score >= 65 or label in {"heavy", "severe"}:
                severe_indices.append(len(samples)-1)
            ann_cursor += d
        # Keep following legs aligned to annotation distance when available.
        if n:
            global_m = max(global_m, ann_cursor)
        closures_count += len(leg.get("closures") or [])
        incidents_count += len(leg.get("incidents") or [])

    if not samples:
        out = dict(empty)
        out["closures_count"] = closures_count
        out["incidents_count"] = incidents_count
        return out

    total_d = sum(x["distance"] for x in samples)
    weighted = sum(x["score"] * x["distance"] for x in samples)
    congested_d = sum(x["distance"] for x in samples if x["score"] >= 65 or x["label"] in {"heavy", "severe"})
    score = weighted / max(total_d, 1)
    level = traffic_level_from_score(score)

    # Map provider distance to the rendered route geometry by physical cumulative
    # distance. This is more stable than mapping annotation index -> polyline index.
    geom_cum = [0.0]
    for i in range(1, len(geometry)):
        try:
            a, b = geometry[i-1], geometry[i]
            geom_cum.append(geom_cum[-1] + haversine_m(float(a[1]), float(a[0]), float(b[1]), float(b[0])))
        except Exception:
            geom_cum.append(geom_cum[-1])
    geom_total = max(1.0, geom_cum[-1])
    provider_total = max(1.0, total_d)

    def geom_index_at(provider_m):
        target = clamp(float(provider_m) / provider_total, 0, 1) * geom_total
        lo, hi = 0, len(geom_cum)-1
        while lo < hi:
            mid = (lo + hi) // 2
            if geom_cum[mid] < target:
                lo = mid + 1
            else:
                hi = mid
        return max(0, min(len(geometry)-1, lo))

    def street_for_distance(mid_m):
        for s in step_ranges:
            if s["start"] <= mid_m <= s["end"] + 1:
                return s["street"]
        return "Trecho da rota"

    def bucket(v):
        if v >= 82: return "severe"
        if v >= 62: return "heavy"
        if v >= 40: return "moderate"
        return "free"

    # Merge contiguous annotations into a complete route traffic ribbon.
    # Free-flow is intentionally kept as orange so the route can transition
    # continuously orange -> yellow -> orange/red without visual gaps.
    merged = []
    for sample in samples:
        b = bucket(sample["score"])
        if merged and merged[-1]["bucket"] == b and sample["start"] - merged[-1]["end"] < 30:
            old_d = merged[-1]["distance"]
            new_d = old_d + sample["distance"]
            merged[-1]["score"] = (merged[-1]["score"] * old_d + sample["score"] * sample["distance"]) / max(1, new_d)
            merged[-1]["distance"] = new_d
            merged[-1]["end"] = sample["end"]
        else:
            merged.append({**sample, "bucket": b})

    segments = []
    for seg in merged[:90]:
        i0 = geom_index_at(seg["start"])
        i1 = max(i0 + 1, geom_index_at(seg["end"]))
        i1 = min(len(geometry)-1, i1)
        coords = geometry[i0:i1+1]
        if len(coords) < 2:
            continue
        mid = (seg["start"] + seg["end"]) / 2
        segments.append({
            "score": round(seg["score"], 1),
            "level": traffic_level_from_score(seg["score"]),
            "bucket": seg["bucket"],
            "street": street_for_distance(mid),
            "distance_start_m": round(seg["start"]),
            "distance_end_m": round(seg["end"]),
            "coordinates": coords,
        })

    # Street-level summaries are computed by overlapping edge annotations with
    # Mapbox steps. This adds no extra API call and lets the UI say which road is
    # slow and how far ahead it begins.
    corridors = []
    for step in step_ranges:
        if step["end"] <= step["start"]:
            continue
        overlap_d = weighted_step = 0.0
        for sample in samples:
            overlap = max(0.0, min(step["end"], sample["end"]) - max(step["start"], sample["start"]))
            if overlap <= 0:
                continue
            overlap_d += overlap
            weighted_step += sample["score"] * overlap
        if overlap_d <= 0:
            continue
        step_score = weighted_step / overlap_d
        if step_score < 40:
            continue
        typical = step.get("duration_typical")
        delay_s = max(0.0, step["duration"] - typical) if typical is not None else 0.0
        item = {
            "street": step["street"],
            "score": round(step_score, 1),
            "level": traffic_level_from_score(step_score),
            "distance_start_m": round(step["start"]),
            "distance_end_m": round(step["end"]),
            "length_m": round(step["end"] - step["start"]),
            "delay_s": round(delay_s),
        }
        # Merge adjacent steps on the same named road.
        if corridors and corridors[-1]["street"] == item["street"] and item["distance_start_m"] - corridors[-1]["distance_end_m"] < 60:
            prev = corridors[-1]
            total_len = max(1, prev["length_m"] + item["length_m"])
            prev["score"] = round((prev["score"]*prev["length_m"] + item["score"]*item["length_m"]) / total_len, 1)
            prev["level"] = traffic_level_from_score(prev["score"])
            prev["distance_end_m"] = item["distance_end_m"]
            prev["length_m"] = total_len
            prev["delay_s"] += item["delay_s"]
        else:
            corridors.append(item)

    # Representative severe points are only for generating provider-side bypass
    # candidates. They are intentionally sparse to avoid extra Directions calls.
    points = []
    last_m = -10**9
    for idx in severe_indices:
        sample = samples[idx]
        mid = (sample["start"] + sample["end"]) / 2
        if mid - last_m < max(180, total_d / 14):
            continue
        gi = geom_index_at(mid)
        c = geometry[gi]
        if len(c) >= 2:
            points.append([float(c[0]), float(c[1])])
            last_m = mid
        if len(points) >= 6:
            break

    live_duration = max(0.0, float(route.get("duration") or 0))
    typical_duration = route.get("duration_typical")
    try:
        typical_duration = max(0.0, float(typical_duration)) if typical_duration is not None else None
    except (TypeError, ValueError):
        typical_duration = None
    delay_s = max(0.0, live_duration - typical_duration) if typical_duration is not None else 0.0
    delay_pct = (delay_s / max(typical_duration, 1) * 100.0) if typical_duration else 0.0

    return {
        "traffic_score": round(score, 1),
        "traffic_level": level,
        "congested_distance_km": round(congested_d/1000.0, 2),
        "traffic_points": points,
        "traffic_segments": segments[:140],
        "traffic_corridors": sorted(corridors, key=lambda x: (x["distance_start_m"], -x["score"]))[:18],
        "severe_segments": len(severe_indices),
        "traffic_delay_min": round(delay_s/60.0, 1),
        "traffic_delay_pct": round(delay_pct, 1),
        "duration_typical": round(typical_duration, 1) if typical_duration is not None else None,
        "closures_count": closures_count,
        "incidents_count": incidents_count,
        "traffic_source": "mapbox-driving-traffic",
    }



def route_live_flow_metrics(route):
    """Cruza a geometria da rota com células anônimas do Vano Maps Live Flow."""
    coords = ((route or {}).get("geometry") or {}).get("coordinates") or []
    if len(coords) < 2:
        return {"live_flow_score": 0, "live_flow_cells": 0, "live_flow_confidence": 0, "live_flow_points": []}
    lons = [float(c[0]) for c in coords if len(c) >= 2]
    lats = [float(c[1]) for c in coords if len(c) >= 2]
    if not lons or not lats:
        return {"live_flow_score": 0, "live_flow_cells": 0, "live_flow_confidence": 0, "live_flow_points": []}
    db = get_db()
    prune_flow_samples(db)
    cutoff = (datetime.now(timezone.utc) - timedelta(minutes=20)).replace(microsecond=0).isoformat()
    pad = 0.004
    rows = db.execute('''
        SELECT cell_lat,cell_lon,direction_bucket,AVG(speed_kmh) avg_speed,COUNT(*) samples,COUNT(DISTINCT source_hash) sources,MAX(created_at) updated_at
        FROM flow_samples
        WHERE created_at>=? AND cell_lat BETWEEN ? AND ? AND cell_lon BETWEEN ? AND ?
        GROUP BY cell_lat,cell_lon,direction_bucket
        HAVING COUNT(DISTINCT source_hash) >= 3
        LIMIT 220
    ''', (cutoff, min(lats)-pad, max(lats)+pad, min(lons)-pad, max(lons)+pad)).fetchall()
    hits = []
    for row in rows:
        d = min_distance_to_geometry_m(float(row["cell_lat"]), float(row["cell_lon"]), coords)
        if d > 190:
            continue
        speed = float(row["avg_speed"] or 0)
        if speed < 8: score = 92
        elif speed < 18: score = 72
        elif speed < 32: score = 48
        else: score = 18
        weight = min(8.0, float(row["sources"] or 0)) * max(0.25, 1.0 - d / 220.0)
        hits.append((score, weight, row, d))
    if not hits:
        return {"live_flow_score": 0, "live_flow_cells": 0, "live_flow_confidence": 0, "live_flow_points": []}
    total_w = sum(x[1] for x in hits)
    score = sum(x[0] * x[1] for x in hits) / max(total_w, 1)
    distinct_sources = sum(min(5, int(x[2]["sources"] or 0)) for x in hits)
    confidence = clamp(18 + distinct_sources * 3.5 + len(hits) * 4, 0, 100)
    points = [{
        "lat": float(row["cell_lat"]), "lon": float(row["cell_lon"]),
        "avg_speed_kmh": round(float(row["avg_speed"] or 0), 1), "sources": int(row["sources"] or 0),
        "traffic_score": int(sc), "distance_to_route_m": round(d), "source": "vano-live-flow",
    } for sc, _w, row, d in sorted(hits, key=lambda x: x[3])[:18]]
    return {"live_flow_score": round(score, 1), "live_flow_cells": len(hits), "live_flow_confidence": round(confidence, 1), "live_flow_points": points}


def traffic_level_from_score(score):
    score = float(score or 0)
    if score < 28: return "Leve"
    if score < 52: return "Moderado"
    if score < 74: return "Intenso"
    return "Muito intenso"

def build_micro_route(base_routes, start_lon, start_lat, end_lon, end_lat, depart_at="now"):
    if not base_routes:
        return None
    fastest = min(base_routes, key=lambda r: float(r.get("duration", 10**12)))
    t = route_traffic_metrics(fastest)
    # O driving-traffic já evita tráfego. A micro-rota só é tentada quando ainda existe
    # um gargalo relevante, evitando chamadas extras desnecessárias.
    if t["traffic_score"] < 42 or not t["traffic_points"] or float(fastest.get("duration", 0)) < 240:
        return None
    try:
        candidates = mapbox_routes(start_lon, start_lat, end_lon, end_lat, "driving", depart_at, t["traffic_points"], alternatives=False)
    except Exception:
        return None
    if not candidates:
        return None
    candidate = candidates[0]
    candidate["_micro_route"] = True
    candidate["_micro_avoided_points"] = len(t["traffic_points"])
    return candidate


def traffic_hotspot_clusters(route, max_clusters=6):
    """Extract block-scale congestion clusters from the provider traffic ribbon.

    The output is intentionally sparse: each point is snapped by Mapbox when used
    as a point exclusion, which lets the provider search side streets around a
    congested block/corridor instead of us inventing off-road geometry.
    """
    traffic = route_traffic_metrics(route)
    segments = [s for s in (traffic.get("traffic_segments") or []) if s.get("bucket") in {"heavy", "severe"}]
    if not segments:
        return []
    clusters = []
    for seg in segments:
        coords = seg.get("coordinates") or []
        if len(coords) < 2:
            continue
        start_m = float(seg.get("distance_start_m") or 0)
        end_m = float(seg.get("distance_end_m") or start_m)
        score = float(seg.get("score") or 0)
        if clusters and start_m - clusters[-1]["end_m"] <= 140:
            c = clusters[-1]
            c["end_m"] = max(c["end_m"], end_m)
            c["score"] = max(c["score"], score)
            c["coordinates"].extend(coords[1:])
            if seg.get("street") and seg.get("street") != "Trecho da rota":
                c["street"] = seg.get("street")
        else:
            clusters.append({
                "start_m": start_m, "end_m": end_m, "score": score,
                "street": seg.get("street") or "Trecho da rota",
                "coordinates": list(coords),
            })
    out = []
    for c in clusters:
        coords = c.pop("coordinates", [])
        if len(coords) < 2:
            continue
        mid = coords[len(coords)//2]
        if len(mid) < 2:
            continue
        span = max(1.0, c["end_m"] - c["start_m"])
        priority = c["score"] * min(2.2, .75 + span/550.0)
        out.append({**c, "point": [float(mid[0]), float(mid[1])], "span_m": round(span), "priority": priority})
    out.sort(key=lambda x: (-x["priority"], x["start_m"]))
    return out[:max_clusters]


def build_fast_micro_routes(base_routes, start_lon, start_lat, end_lon, end_lat, depart_at="now"):
    """Generate ETA-only block bypasses in parallel around live congestion.

    Important: fastest mode never consults the Safety Engine. The provider ETA is
    still the sole winner criterion. Small block-level deviations are *not* thrown
    away merely because they overlap most of the original route.
    """
    if not base_routes:
        return []
    fastest = min(base_routes, key=lambda r: float(r.get("duration", 10**12)))
    baseline_s = max(1.0, float(fastest.get("duration") or 1))
    traffic = route_traffic_metrics(fastest)
    clusters = traffic_hotspot_clusters(fastest, max_clusters=6)
    if baseline_s < 150 or not clusters:
        return []
    if float(traffic.get("traffic_score") or 0) < 32 and int(traffic.get("severe_segments") or 0) == 0:
        return []

    groups = []
    # One hotspot = true block-scale bypass.
    for c in clusters[:4]:
        groups.append({"points": [c["point"]], "kind": "block", "labels": [c["street"]]})
    # Long jams often need a corridor escape instead of one side street.
    if len(clusters) >= 2:
        groups.append({"points": [clusters[0]["point"], clusters[1]["point"]], "kind": "corridor", "labels": [clusters[0]["street"], clusters[1]["street"]]})
    if len(clusters) >= 3 and float(traffic.get("traffic_score") or 0) >= 58:
        groups.append({"points": [c["point"] for c in clusters[:3]], "kind": "corridor", "labels": [c["street"] for c in clusters[:3]]})
    groups = groups[:6]

    def fetch(spec):
        try:
            found = mapbox_routes(
                start_lon, start_lat, end_lon, end_lat, "driving", depart_at,
                exclusions=spec["points"], alternatives=False, extra_excludes=None,
            )
            if not found:
                return None
            candidate = found[0]
            # Avoid pathological detours, but allow a candidate to be slower: the
            # final selector will simply ignore it if it does not beat the ETA.
            if float(candidate.get("duration") or 10**12) > baseline_s * 1.42:
                return None
            candidate["_micro_route"] = True
            candidate["_micro_avoided_points"] = len(spec["points"])
            candidate["_micro_strategy"] = spec["kind"]
            candidate["_micro_streets"] = list(dict.fromkeys(spec["labels"]))[:3]
            candidate["_fast_eta_only"] = True
            candidate["_eta_gain_s"] = round(baseline_s - float(candidate.get("duration") or baseline_s), 1)
            return candidate
        except Exception:
            return None

    with ThreadPoolExecutor(max_workers=min(6, len(groups))) as pool:
        fetched = list(pool.map(fetch, groups))

    # Exact duplicates are useless, but 97-99% overlap can be precisely the useful
    # one-block shortcut the user asked for, so do not apply broad overlap pruning.
    seen = {route_signature(r) for r in base_routes}
    out = []
    for candidate in fetched:
        if not candidate:
            continue
        sig = route_signature(candidate)
        if sig and sig in seen:
            continue
        seen.add(sig)
        out.append(candidate)
    out.sort(key=lambda r: float(r.get("duration") or 10**12))
    return out[:6]


def build_dense_micro_route_pool(base_routes, start_lon, start_lat, end_lon, end_lat, depart_at="now", budget=8, base_exclusions=None, extra_excludes=None):
    """Generate a bounded but broad pool of block/corridor micro-routes.

    There is no finite way to request literally every street combination from a
    routing provider. Instead, V45 enumerates the useful combinations around the
    strongest live congestion clusters (single blocks, adjacent pairs and short
    corridors), requests them in parallel and keeps every exact-distinct route
    that remains within a sane detour ceiling. The normal mode selector still
    decides the winner afterwards.
    """
    base = list(base_routes or [])
    if not base:
        return []
    requested_budget = max(2, min(12, int(budget or 8)))
    baseline = min(base, key=lambda r: float(r.get("duration") or 10**12))
    baseline_s = max(1.0, float(baseline.get("duration") or 1))
    baseline_t = route_traffic_metrics(baseline)
    baseline_score = float(baseline_t.get("traffic_score") or 0)
    severe_count = int(baseline_t.get("severe_segments") or 0)
    # V88: do not spend several provider calls on short/light trips. Increase
    # exploration only when live congestion is strong enough to justify it.
    if baseline_s < 300:
        return []
    if baseline_score < 34 and severe_count == 0:
        return []
    if baseline_score >= 82 or severe_count >= 5:
        dynamic_budget = 6
    elif baseline_score >= 68 or severe_count >= 3:
        dynamic_budget = 5
    elif baseline_score >= 52 or severe_count >= 2:
        dynamic_budget = 4
    else:
        dynamic_budget = 2
    budget = min(requested_budget, dynamic_budget)

    seeds = select_diverse_routes(base, max_routes=2, max_overlap=.965, sort_key=lambda r: float(r.get("duration") or 10**12))
    specs = []

    def add_spec(points, kind, streets):
        clean = []
        for point in points or []:
            try:
                lon, lat = float(point[0]), float(point[1])
            except Exception:
                continue
            if not (-180 <= lon <= 180 and -90 <= lat <= 90):
                continue
            if all(haversine_m(lat, lon, q[1], q[0]) > 55 for q in clean):
                clean.append([lon, lat])
        if not clean:
            return
        key = tuple((round(x[0], 4), round(x[1], 4)) for x in clean[:4])
        if any(x["key"] == key for x in specs):
            return
        specs.append({"key": key, "points": clean[:4], "kind": kind, "streets": list(dict.fromkeys(streets or []))[:4]})

    for seed_idx, seed in enumerate(seeds):
        clusters = traffic_hotspot_clusters(seed, max_clusters=6)
        # Interleave strategy families before applying the global budget. That way
        # a busy corridor cannot spend every request on single-point exclusions and
        # we always probe both block-scale and multi-block escapes.
        for c in clusters[:4]:
            add_spec([c["point"]], "block", [c.get("street") or "Trecho congestionado"])
        for i in range(min(3, max(0, len(clusters)-1))):
            add_spec([clusters[i]["point"], clusters[i+1]["point"]], "adjacent-blocks", [clusters[i].get("street"), clusters[i+1].get("street")])
        if len(clusters) >= 3:
            for i in range(min(2, len(clusters)-2)):
                window = clusters[i:i+3]
                add_spec([c["point"] for c in window], "short-corridor", [c.get("street") for c in window])
        # Skip-one combinations catch the common pattern where one side street is
        # blocked but the next parallel block still beats the congested corridor.
        for i in range(min(2, max(0, len(clusters)-2))):
            add_spec([clusters[i]["point"], clusters[i+2]["point"]], "parallel-blocks", [clusters[i].get("street"), clusters[i+2].get("street")])
        if seed_idx == 0 and baseline_score >= 58 and len(clusters) >= 4:
            add_spec([clusters[0]["point"], clusters[2]["point"], clusters[3]["point"]], "corridor-escape", [clusters[0].get("street"), clusters[2].get("street"), clusters[3].get("street")])
            add_spec([clusters[1]["point"], clusters[2]["point"], clusters[4]["point"]] if len(clusters) >= 5 else [clusters[1]["point"], clusters[2]["point"], clusters[3]["point"]], "corridor-escape", [clusters[1].get("street"), clusters[2].get("street"), clusters[min(4, len(clusters)-1)].get("street")])

    # If provider traffic was summarized but did not form named clusters, still
    # explore its sparse representative severe points.
    if not specs:
        for point in (baseline_t.get("traffic_points") or [])[:5]:
            add_spec([point], "traffic-point", ["Gargalo detectado"])
    specs = specs[:budget]
    if not specs:
        return []

    def fetch(spec):
        try:
            exclusions = (list(base_exclusions or []) + list(spec["points"]))[:18]
            found = mapbox_routes(
                start_lon, start_lat, end_lon, end_lat, "driving", depart_at,
                exclusions=exclusions, alternatives=False, extra_excludes=extra_excludes,
            )
            if not found:
                return None
            candidate = found[0]
            duration = float(candidate.get("duration") or 10**12)
            if duration > baseline_s * 1.48:
                return None
            after = route_traffic_metrics(candidate)
            after_score = float(after.get("traffic_score") or 0)
            # V88 micro-routes are time-saving candidates, not scenic traffic
            # relief. Safety detours are handled by the safety engine separately.
            eta_gain = baseline_s - duration
            relief = baseline_score - after_score
            min_gain = 30 if baseline_s >= 1200 else 20 if baseline_s >= 600 else 12
            if eta_gain < min_gain:
                return None
            candidate["_micro_route"] = True
            candidate["_micro_avoided_points"] = len(spec["points"])
            candidate["_micro_strategy"] = spec["kind"]
            candidate["_micro_streets"] = [x for x in spec["streets"] if x][:4]
            candidate["_micro_traffic_relief"] = round(relief, 1)
            candidate["_micro_baseline_traffic"] = round(baseline_score, 1)
            candidate["_micro_traffic_score"] = round(after_score, 1)
            candidate["_eta_gain_s"] = round(eta_gain, 1)
            return candidate
        except Exception:
            return None

    with ThreadPoolExecutor(max_workers=min(4, len(specs))) as pool:
        fetched = list(pool.map(fetch, specs))

    seen = {route_signature(r) for r in base if route_signature(r)}
    out = []
    for candidate in fetched:
        if not candidate:
            continue
        sig = route_signature(candidate)
        if sig and sig in seen:
            continue
        if sig:
            seen.add(sig)
        out.append(candidate)
    out.sort(key=lambda r: (
        float(r.get("duration") or 10**12),
        -float(r.get("_micro_traffic_relief") or 0),
    ))
    return out[:budget]


def fast_route_payload(route, idx, travel_profile="driving"):
    """Minimal route enrichment for the ETA-only fast engine."""
    traffic = route_traffic_metrics(route) if is_motorized_profile(travel_profile) else {
        "traffic_score": 0, "traffic_level": "—", "congested_distance_km": 0,
        "severe_segments": 0, "traffic_segments": [],
    }
    road = route_road_controls(route)
    return {
        "id": idx,
        "distance": route.get("distance", 0),
        "duration": route.get("duration", 0),
        "duration_min": round(float(route.get("duration", 0)) / 60, 1),
        "geometry": route.get("geometry"),
        "steps": compact_steps(route),
        "profile": travel_profile,
        "micro_route": bool(route.get("_micro_route")),
        "micro_avoided_points": int(route.get("_micro_avoided_points", 0) or 0),
        "micro_strategy": route.get("_micro_strategy") or "",
        "micro_streets": route.get("_micro_streets") or [],
        "micro_traffic_relief": round(float(route.get("_micro_traffic_relief") or 0), 1),
        "micro_baseline_traffic": round(float(route.get("_micro_baseline_traffic") or 0), 1),
        "micro_traffic_score": round(float(route.get("_micro_traffic_score") or 0), 1),
        "eta_gain_s": round(float(route.get("_eta_gain_s") or 0), 1),
        "eta_gain_min": round(max(0.0, float(route.get("_eta_gain_s") or 0))/60.0, 1),
        "adaptive_variant": bool(route.get("_adaptive_variant")),
        "adaptive_avoided_points": int(route.get("_adaptive_avoided_points", 0) or 0),
        "routing_profile_used": route.get("_profile_used", ""),
        "routing_provider": route.get("_provider", "mapbox"),
        "route_signature": route_signature(route),
        "fast_eta_only": True,
        "badges": [],
        # Compatibility fields: the fast engine intentionally does not calculate safety.
        "safety_score": None, "safety_conservative_score": None, "safety_level": None,
        "safety_level_label": "Não analisado no modo Rápida",
        "data_confidence": 0, "decision_confidence": 0, "risk_exposure_pct": 0,
        "hotspot_risk": 0, "risk_zones": [], "risk_factors": [], "nearby_alerts": [],
        "quiet_score": 0, "vano_score": 0,
        **{k: v for k, v in traffic.items() if k != "traffic_points"},
        **road,
    }


def compact_steps(route):
    steps = []
    for leg in route.get("legs", []):
        for step in leg.get("steps", []):
            maneuver = step.get("maneuver") or {}
            controls = []
            for inter in step.get("intersections", []) or []:
                loc = inter.get("location") or []
                if len(loc) < 2:
                    continue
                base = {"lon": float(loc[0]), "lat": float(loc[1])}
                if inter.get("traffic_signal"):
                    controls.append({**base, "type": "traffic_signal", "label": "Semáforo"})
                if inter.get("stop_sign"):
                    controls.append({**base, "type": "stop_sign", "label": "Parada obrigatória"})
                if inter.get("yield_sign"):
                    controls.append({**base, "type": "yield_sign", "label": "Dê a preferência"})
                if inter.get("railway_crossing"):
                    controls.append({**base, "type": "railway_crossing", "label": "Cruzamento ferroviário"})
                toll = inter.get("toll_collection") or {}
                if toll:
                    controls.append({**base, "type": "toll", "label": toll.get("name") or "Pedágio"})
            lane_guidance = []
            for inter in step.get("intersections", []) or []:
                lanes = inter.get("lanes") or []
                if lanes:
                    lane_guidance = [{
                        "indications": list(lane.get("indications") or [])[:4],
                        "valid": bool(lane.get("valid")),
                        "active": bool(lane.get("active")),
                    } for lane in lanes[:10]]
                    # A interseção mais próxima do fim do step costuma ser a útil para a manobra.
            steps.append({
                "instruction": maneuver.get("instruction") or "Continue pela rota",
                "name": step.get("name") or "",
                "type": maneuver.get("type", ""),
                "modifier": maneuver.get("modifier", ""),
                "distance": round(float(step.get("distance", 0)), 1),
                "duration": round(float(step.get("duration", 0)), 1),
                "duration_typical": round(float(step.get("duration_typical", 0)), 1) if step.get("duration_typical") is not None else None,
                "bearing_after": maneuver.get("bearing_after"),
                "exit": maneuver.get("exit"),
                "lanes": lane_guidance,
                "speed_limit_sign": step.get("speedLimitSign"),
                "speed_limit_unit": step.get("speedLimitUnit"),
                "controls": controls[:24],
                "voice_prompts": [{
                    "distance": round(float(v.get("distanceAlongGeometry", 0)), 1),
                    "announcement": str(v.get("announcement") or "")[:280],
                } for v in (step.get("voiceInstructions") or [])[:5] if v.get("announcement")],
            })
    # Rotas interestaduais/internacionais podem ter centenas de manobras.
    return steps[:700]


def route_road_controls(route):
    controls = []
    seen = set()
    maxspeeds = []
    incident_count = 0
    closure_count = 0
    for leg in route.get("legs", []) or []:
        incident_count += len(leg.get("incidents") or [])
        closure_count += len(leg.get("closures") or [])
        ann = leg.get("annotation") or {}
        maxspeeds.extend(ann.get("maxspeed") or [])
        for step in leg.get("steps", []) or []:
            for inter in step.get("intersections", []) or []:
                loc = inter.get("location") or []
                if len(loc) < 2:
                    continue
                lon, lat = round(float(loc[0]), 6), round(float(loc[1]), 6)
                types = []
                if inter.get("traffic_signal"): types.append(("traffic_signal", "Semáforo"))
                if inter.get("stop_sign"): types.append(("stop_sign", "Parada obrigatória"))
                if inter.get("yield_sign"): types.append(("yield_sign", "Dê a preferência"))
                if inter.get("railway_crossing"): types.append(("railway_crossing", "Cruzamento ferroviário"))
                toll = inter.get("toll_collection") or {}
                if toll: types.append(("toll", toll.get("name") or "Pedágio"))
                for kind, label in types:
                    key = (kind, lon, lat)
                    if key in seen:
                        continue
                    seen.add(key)
                    controls.append({"type": kind, "label": label, "lon": lon, "lat": lat, "source": "mapbox"})
    known_limits = []
    speed_limit_points = []
    geometry = (route.get("geometry") or {}).get("coordinates") or []
    last_limit = None
    for idx, item in enumerate(maxspeeds):
        if isinstance(item, dict) and item.get("speed") is not None:
            entry = {"speed": item.get("speed"), "unit": item.get("unit") or "km/h"}
            known_limits.append(entry)
            current = (entry["speed"], entry["unit"])
            if current != last_limit and geometry:
                gi = min(max(0, idx), len(geometry)-1)
                speed_limit_points.append({"index": gi, "lon": float(geometry[gi][0]), "lat": float(geometry[gi][1]), **entry})
                last_limit = current
    return {
        "road_controls": controls[:500],
        "road_controls_count": len(controls),
        "known_speed_limits": known_limits[:120],
        "speed_limit_points": speed_limit_points[:220],
        "incidents_count": incident_count,
        "closures_count": closure_count,
    }



